import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { withBasePath } from "@/lib/site-path";
import { ArrowLeft, ArrowRight, Camera, CheckCircle, HandTap, MapPin, SunHorizon, UsersThree, WhatsappLogo, X } from "@phosphor-icons/react/dist/ssr";

export const metadata: Metadata = { title: "Private Trip Pantai Malang | Aligatour", description: "Private Trip Pantai Malang Selatan mulai Rp200.000 per orang, bebas memilih maksimal dua pantai dengan mobil, driver, guide, tiket, dan dokumentasi." };

const prices = [[1,"1.395.000"],[2,"695.000"],[3,"465.000"],[4,"345.000"],[5,"275.000"],[6,"235.000"],[7,"220.000"],[8,"295.000"],[9,"275.000"],[10,"235.000"],[11,"220.000"],[12,"200.000"]];
const destinations = [
  { name: "Pantai Tanjung Penyu", image: withBasePath("/destinations/pantai-malang/pantai-tanjung-penyu.webp") },
  { name: "Pantai Ungapan", image: withBasePath("/destinations/pantai-malang/pantai-ungapan.webp") },
  { name: "Pantai Goa Cina", image: withBasePath("/destinations/pantai-malang/pantai-goa-cina.webp") },
  { name: "Pantai Balekambang", image: withBasePath("/destinations/pantai-malang/pantai-balekambang.webp") },
  { name: "Pantai Teluk Asmara", image: withBasePath("/destinations/pantai-malang/pantai-teluk-asmara.webp") },
  { name: "Pantai Batu Bengkung", image: withBasePath("/destinations/pantai-malang/pantai-batu-bengkung.webp") },
];
const includes = ["Mobil", "BBM", "Driver", "Antar jemput", "Guide sekaligus fotografer", "Dokumentasi foto & video reels", "Tiket masuk untuk dua destinasi pantai"];
const excludes = ["Transportasi dari kota asal ke meeting point", "Hotel", "Keperluan pribadi"];

export default function PrivateTripPantaiMalangPage() {
  return <main className="min-h-screen bg-[#fbfcf8]">
    <section className="relative min-h-[610px] overflow-hidden bg-[#153d37] text-white"><Image src={withBasePath("/trip-cards/pantai-malang.webp")} alt="Pantai Malang Selatan" fill priority sizes="100vw" className="object-cover opacity-65"/><div className="absolute inset-0 bg-gradient-to-r from-[#063d45]/95 via-[#063d45]/68 to-[#063d45]/15"/><div className="container relative z-10 py-7"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-white/80"><ArrowLeft/> Kembali ke beranda</Link></div><div className="container relative z-10 pb-20 pt-16"><span className="inline-flex items-center gap-2 rounded-full bg-[#ffd15b] px-4 py-2 text-xs font-extrabold uppercase tracking-wider text-[#153d37]"><SunHorizon weight="fill"/> Private Trip · Pantai Malang</span><h1 className="mt-6 max-w-4xl text-5xl font-extrabold tracking-[-.04em] sm:text-7xl">Bebas pilih pantai,<br/><span className="text-[#ffd15b]">bebas buat cerita.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/75">Tentukan maksimal dua pantai tujuan di Malang Selatan untuk perjalanan private bersama rombonganmu.</p><div className="mt-8 flex flex-wrap items-end gap-7"><div><small className="text-white/60">Mulai dari · per orang</small><p className="text-3xl font-extrabold text-[#ffd15b]">Rp200.000</p></div><a href="#pricelist" className="btn-primary">Lihat pricelist <UsersThree size={20} weight="fill"/></a></div></div></section>
    <section className="relative z-10 -mt-9"><div className="container"><div className="grid overflow-hidden rounded-2xl bg-white shadow-2xl shadow-[#153d3720] sm:grid-cols-3">{[[MapPin,"Meeting point","Kota Malang & Kota Batu"],[SunHorizon,"Destinasi","Bebas pilih maks. 2 pantai"],[UsersThree,"Kapasitas","1–12 peserta"]].map(([Icon,label,value])=><div key={label as string} className="flex items-center gap-4 border-b border-[#e8ece6] p-6 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><Icon size={27} weight="fill" className="shrink-0 text-[#176b5b]"/><div><small className="text-[#81908c]">{label as string}</small><b className="block">{value as string}</b></div></div>)}</div></div></section>
    <section className="py-24"><div className="container"><div className="flex flex-wrap items-end justify-between gap-6"><div className="max-w-2xl"><p className="eyebrow">Pantai Tujuan</p><h2 className="mt-3 text-4xl font-extrabold">Pilih dua pantai favoritmu.</h2><p className="mt-5 leading-7 text-[#6d7d78]">Berikut beberapa destinasi populer di Malang Selatan. Pilihan pantai lain dapat dikonsultasikan bersama tim Aligatour.</p></div><div className="rounded-2xl bg-[#eef1e6] px-5 py-4"><div className="flex items-center gap-3"><SunHorizon size={27} weight="fill" className="text-[#176b5b]"/><div><b className="block text-sm">Maksimal 2 destinasi</b><span className="text-xs text-[#6d7d78]">Keberangkatan setiap hari</span></div></div></div></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{destinations.map((destination,index)=><article key={destination.name} className="group overflow-hidden rounded-[22px] border border-[#dfe6df] bg-white"><div className="relative h-52 overflow-hidden"><Image src={destination.image} alt={destination.name} fill sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw" className="object-cover transition duration-500 group-hover:scale-105"/><span className="absolute left-4 top-4 flex h-9 w-9 items-center justify-center rounded-full bg-[#ffd15b] text-sm font-extrabold text-[#153d37]">{index+1}</span></div><div className="flex items-center justify-between gap-3 p-5"><div><span className="text-xs font-bold uppercase tracking-wider text-[#81908c]">Pilihan destinasi</span><h3 className="mt-1 text-lg font-extrabold">{destination.name}</h3></div><SunHorizon size={25} weight="fill" className="shrink-0 text-[#176b5b]"/></div></article>)}</div><p className="mt-6 text-center text-sm text-[#6d7d78]">Sudah punya pantai tujuan lain? Sampaikan saat konsultasi itinerary.</p></div></section>
    <section id="pricelist" className="bg-[#f0f0e5] py-24"><div className="container"><div className="text-center"><p className="eyebrow">Harga Per Orang</p><h2 className="mt-3 text-4xl font-extrabold">Makin ramai, makin hemat.</h2><p className="mt-3 text-[#6d7d78]">Harga menyesuaikan jumlah peserta dalam satu perjalanan private.</p><div className="mx-auto mt-5 inline-flex items-center gap-2 rounded-full bg-[#d8f05a] px-4 py-2 text-sm font-extrabold text-[#153d37]"><HandTap size={20} weight="fill"/> Ketuk jumlah peserta untuk reservasi</div></div><div className="mx-auto mt-8 grid max-w-5xl grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{prices.map(([people,price])=><a key={people} href={`https://wa.me/628563532918?text=${encodeURIComponent(`Halo Aligatour, saya tertarik Private Trip Pantai Malang untuk ${people} orang.`)}`} aria-label={`Reservasi Private Trip Pantai Malang untuk ${people} orang seharga Rp${price} per orang`} className="group overflow-hidden rounded-2xl border-2 border-[#d7ded4] bg-white transition active:scale-[.98] hover:-translate-y-1 hover:border-[#176b5b]"><div className="p-4 pb-3 sm:p-5 sm:pb-4"><div className="flex items-center gap-2 text-sm font-bold text-[#51635e]"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[#eef1e6]"><UsersThree size={17} weight="fill"/></span>{people} orang</div><b className="mt-3 block text-lg text-[#176b5b] sm:text-xl">Rp{price}</b><span className="text-xs text-[#81908c]">per orang</span></div><div className="flex items-center justify-between bg-[#153d37] px-4 py-3 text-xs font-extrabold text-white sm:px-5"><span className="flex items-center gap-1.5"><WhatsappLogo size={17} weight="fill"/> Pilih paket</span><ArrowRight size={17} className="text-[#d8f05a]"/></div></a>)}</div><p className="mx-auto mt-5 max-w-2xl text-center text-xs leading-5 text-[#73827e]">*Harga 8 orang ditampilkan sesuai pricelist resmi. Konfirmasikan kembali nominal akhir melalui WhatsApp saat reservasi.</p></div></section>
    <section className="bg-[#153d37] py-20 text-white"><div className="container grid gap-6 md:grid-cols-2"><div className="rounded-[26px] border border-white/12 bg-white/5 p-7"><h2 className="text-2xl font-extrabold">Sudah termasuk</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{includes.map(item=><div key={item} className="flex gap-3"><CheckCircle size={21} weight="fill" className="shrink-0 text-[#ffd15b]"/><span>{item}</span></div>)}</div></div><div className="rounded-[26px] bg-white p-7 text-[#153d37]"><h2 className="text-2xl font-extrabold">Belum termasuk</h2><div className="mt-6 space-y-4">{excludes.map(item=><div key={item} className="flex gap-3"><X size={20} weight="bold" className="shrink-0 text-[#b96a4c]"/><span>{item}</span></div>)}</div><div className="mt-7 rounded-xl bg-[#eef1e6] p-4 text-sm"><b>Penjemputan Surabaya</b><span className="mt-1 block text-[#60716c]">Tambahan Rp450.000 per mobil.</span></div></div></div></section>
    <section className="container my-10 rounded-[30px] bg-[#ffd15b] p-9 sm:p-12"><div className="flex flex-wrap items-center justify-between gap-7"><div><div className="flex items-center gap-2 font-bold"><Camera size={23} weight="fill"/> Guide sekaligus fotografer</div><h2 className="mt-2 text-3xl font-extrabold">Pantai mana yang ingin kamu kunjungi?</h2><p className="mt-2 text-[#38564f]">Konsultasikan dua pilihan pantai dan jumlah rombonganmu.</p></div><a href="https://wa.me/628563532918?text=Halo%20Aligatour%2C%20saya%20ingin%20konsultasi%20Private%20Trip%20Pantai%20Malang." className="btn-dark"><WhatsappLogo size={20} weight="fill"/> Konsultasi trip</a></div></section>
  </main>;
}
