import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, Car, Check, CheckCircle, CookingPot, IdentificationCard, MapPin, Mountains, ShieldCheck, Tent, UsersThree, WhatsappLogo, X } from "@phosphor-icons/react/dist/ssr";

export const metadata: Metadata = {
  title: "Private Trip Ranu Kumbolo | Aligatour",
  description: "Private Trip Ranu Kumbolo 2 hari 1 malam mulai Rp2.200.000 per grup untuk 2–4 orang, lengkap dengan transportasi, SIMAKSI, konsumsi, dan perlengkapan pendakian.",
};

const includeGroups = [
  { title: "Transportasi & Perizinan", description: "Perjalanan dan administrasi kawasan", icon: Car, items: ["Transportasi Malang–Ranu Pane PP", "Driver, BBM, dan parkir", "Surat Izin Masuk Kawasan (SIMAKSI)", "Asuransi TNBTS"] },
  { title: "Tim Perjalanan", description: "Pendamping selama trip berlangsung", icon: UsersThree, items: ["Tour Leader", "Pendamping pendakian", "Porter tim untuk alat dan logistik", "Dokumentasi"] },
  { title: "Perlengkapan Camping", description: "Peralatan kelompok yang telah disiapkan", icon: Tent, items: ["Tenda kapasitas 4 orang, diisi 3 orang", "Matras lipat untuk 2–4 orang", "Kursi dan meja lipat", "Alat masak kelompok", "P3K standar", "Handwarmer"] },
  { title: "Konsumsi", description: "Makan dan minum selama perjalanan", icon: CookingPot, items: ["Makan sebelum pendakian 1 kali", "Makan selama pendakian 3 kali", "Makan setelah pendakian 1 kali", "Welcome Snack & Drink", "Fresh Fruits"] },
];

const excludes = ["Transportasi menuju meeting point", "Surat sehat", "Sleeping bag", "Obat pribadi", "Camilan pribadi", "Porter pribadi", "Perlengkapan camping pribadi", "Hal yang tidak disebutkan dalam include"];

const facilities = [
  { title: "Full Powerbank", image: "/facilities/powerbank.webp" },
  { title: "Free Wi-Fi", image: "/facilities/wifi.webp" },
  { title: "Insta360 X4 Air", note: "Terbatas", image: "/facilities/insta360-x4.webp" },
  { title: "Insta360 Ace Pro 2", note: "Terbatas", image: "/facilities/insta360-ace.webp" },
  { title: "Gimbal", note: "Terbatas", image: "/facilities/gimbal.webp" },
];

const packageFeatures = ["Menginap 1 malam", "Handwarmer", "Pijat setelah trip", "Sleeping bag", "Surat sehat", "Camilan pribadi", "Porter pribadi", "Fotografer pribadi", "Gratis trip promo"];
const packages = [
  { name: "Ekonomis", price: "2.200.000", meal: "Paket makanan standar", highlight: "Pilih 1 fasilitas unggulan", unavailable: ["Pijat setelah trip", "Sleeping bag", "Surat sehat", "Camilan pribadi", "Porter pribadi", "Fotografer pribadi", "Gratis trip promo"] },
  { name: "Exclusive", price: "2.500.000", meal: "Daging grill premium", highlight: "Pilih 1 fasilitas unggulan", unavailable: ["Porter pribadi", "Fotografer pribadi", "Gratis trip promo"], recommended: true },
  { name: "Luxury", price: "2.600.000", meal: "Chef pribadi", highlight: "Semua fasilitas unggulan", unavailable: [] },
];

export default function PrivateTripRanuKumboloPage() {
  return <main className="min-h-screen bg-[#fbfcf8]">
    <section className="relative min-h-[620px] overflow-hidden bg-[#153d37] text-white">
      <Image src="/trip-cards/ranu-kumbolo.jpg" alt="Danau Ranu Kumbolo" fill priority sizes="100vw" className="object-cover opacity-60"/>
      <div className="absolute inset-0 bg-gradient-to-r from-[#102f2b]/95 via-[#102f2b]/68 to-[#102f2b]/20"/>
      <div className="container relative z-10 py-7"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-white/80"><ArrowLeft/> Kembali ke beranda</Link></div>
      <div className="container relative z-10 pb-20 pt-16"><span className="inline-flex items-center gap-2 rounded-full bg-[#d8f05a] px-4 py-2 text-xs font-extrabold uppercase tracking-wider text-[#153d37]"><Mountains weight="fill"/> Private Trip · 2 Hari 1 Malam</span><h1 className="mt-6 max-w-4xl text-5xl font-extrabold tracking-[-.04em] sm:text-7xl">Ranu Kumbolo,<br/><span className="text-[#d8f05a]">lebih dekat bersama.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/75">Perjalanan private menuju salah satu danau terindah di Semeru, dirancang untuk grup kecil agar lebih nyaman dan personal.</p><div className="mt-8 flex flex-wrap items-end gap-7"><div><small className="text-white/60">Mulai dari · per grup 2–4 orang</small><p className="text-3xl font-extrabold text-[#d8f05a]">Rp2.200.000</p></div><a href="#packages" className="btn-primary">Pilih paket <UsersThree size={20} weight="fill"/></a></div></div>
    </section>

    <section className="relative z-10 -mt-9"><div className="container"><div className="grid overflow-hidden rounded-2xl bg-white shadow-2xl shadow-[#153d3720] sm:grid-cols-3">{[[UsersThree,"Peserta","Minimal 2 · Maksimal 4"],[Mountains,"Durasi","2 hari 1 malam"],[MapPin,"Rute","Malang ↔ Ranu Pane"]].map(([Icon,label,value])=><div key={label as string} className="flex items-center gap-4 border-b border-[#e8ece6] p-6 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><Icon size={27} weight="fill" className="shrink-0 text-[#176b5b]"/><div><small className="text-[#81908c]">{label as string}</small><b className="block">{value as string}</b></div></div>)}</div></div></section>

    <section className="py-24"><div className="container"><div className="mb-10 max-w-2xl"><p className="eyebrow">Fasilitas Unggulan</p><h2 className="mt-3 text-4xl font-extrabold">Dokumentasikan setiap langkah.</h2><p className="mt-4 text-[#6d7d78]">Paket Luxury memperoleh seluruh fasilitas unggulan. Paket Exclusive dan Ekonomis dapat memilih satu fasilitas.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{facilities.map(item=><article key={item.title} className="overflow-hidden rounded-xl border border-[#dfe6df] bg-white"><div className="relative h-36 bg-[#f3f1e8]"><Image src={item.image} alt={item.title} fill sizes="(max-width: 640px) 50vw, 200px" className="object-contain p-3"/></div><div className="min-h-20 p-4"><b className="text-sm">{item.title}</b>{item.note&&<span className="mt-1 block text-xs font-bold text-[#176b5b]">{item.note}</span>}</div></article>)}</div></div></section>

    <section className="bg-[#153d37] py-24 text-white"><div className="container"><div className="max-w-2xl"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#d8f05a]">Sudah Termasuk</p><h2 className="mt-3 text-4xl font-extrabold">Kami urus kebutuhan perjalananmu.</h2><p className="mt-4 leading-7 text-white/65">Fasilitas dikelompokkan agar kamu lebih mudah melihat apa saja yang sudah disiapkan.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2">{includeGroups.map(group=><article key={group.title} className="rounded-[24px] border border-white/12 bg-white/5 p-6"><div className="flex items-start gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-[#d8f05a] text-[#153d37]"><group.icon size={25} weight="fill"/></span><div><h3 className="text-xl font-extrabold">{group.title}</h3><p className="mt-1 text-sm text-white/50">{group.description}</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{group.items.map(item=><div key={item} className="flex gap-2.5 text-sm leading-6 text-white/80"><CheckCircle size={19} weight="fill" className="mt-0.5 shrink-0 text-[#d8f05a]"/><span>{item}</span></div>)}</div></article>)}</div><div className="mt-6 rounded-[24px] bg-white p-6 text-[#153d37] sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-extrabold">Belum termasuk</h2><p className="mt-1 text-sm text-[#6d7d78]">Kebutuhan pribadi yang perlu disiapkan peserta.</p></div><span className="rounded-full bg-[#fff1eb] px-3 py-1.5 text-xs font-extrabold text-[#a85438]">PERSONAL</span></div><div className="mt-6 grid gap-x-8 gap-y-3 sm:grid-cols-2 lg:grid-cols-4">{excludes.map(item=><div key={item} className="flex gap-2.5 text-sm"><X size={19} weight="bold" className="shrink-0 text-[#b96a4c]"/><span>{item}</span></div>)}</div></div></div></section>

    <section id="packages" className="py-24"><div className="container"><div className="text-center"><p className="eyebrow">Pilihan Paket</p><h2 className="mt-3 text-4xl font-extrabold">Pilih pengalaman Ranu Kumbolo</h2><p className="mt-3 text-[#6d7d78]">Semua harga berlaku per grup berisi 2–4 orang.</p></div><div className="mt-12 grid items-stretch gap-6 lg:grid-cols-3">{packages.map(pkg=><article key={pkg.name} className={`relative flex flex-col rounded-[28px] border bg-white p-7 ${pkg.recommended?"border-[#176b5b] shadow-xl shadow-[#153d3718] lg:-translate-y-3":"border-[#dfe6df]"}`}>{pkg.recommended&&<span className="absolute right-5 top-5 rounded-full bg-[#d8f05a] px-3 py-1 text-xs font-extrabold">PALING POPULER</span>}<h3 className="text-2xl font-extrabold">{pkg.name}</h3><p className="mt-1 text-sm text-[#6d7d78]">2 hari 1 malam</p><p className="mt-6 text-4xl font-extrabold text-[#176b5b]">Rp{pkg.price}<span className="text-sm font-medium text-[#6d7d78]"> /grup</span></p><div className="my-6 h-px bg-[#e7ebe5]"/><div className="rounded-xl bg-[#f0f3e9] p-4 text-sm"><b className="block">{pkg.meal}</b><span className="mt-1 block text-[#60716c]">{pkg.highlight}</span></div><div className="mt-6 flex-1 space-y-3">{packageFeatures.map(feature=>{const unavailable=pkg.unavailable.includes(feature);return <div key={feature} className={`flex gap-3 text-sm ${unavailable?"text-gray-400":"text-[#153d37]"}`}>{unavailable?<X size={19} className="shrink-0"/>:<Check size={19} weight="bold" className="shrink-0 text-[#176b5b]"/>}<span className={unavailable?"line-through":""}>{feature}</span></div>})}</div><a href={`https://wa.me/628563532918?text=${encodeURIComponent(`Halo Aligatour, saya tertarik paket ${pkg.name} Private Trip Ranu Kumbolo untuk grup 2–4 orang.`)}`} className={pkg.recommended?"btn-primary mt-8":"btn-dark mt-8 justify-center"}><WhatsappLogo size={20} weight="fill"/> Reservasi {pkg.name}</a></article>)}</div></div></section>

    <section className="bg-[#f0f0e5] py-20"><div className="container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Ketentuan Booking</p><h2 className="mt-3 text-4xl font-extrabold">Persiapkan perjalananmu.</h2><p className="mt-4 leading-7 text-[#6d7d78]">Terbuka untuk umum, grup, maupun perusahaan. Admin akan membantu proses booking dan SIMAKSI melalui WhatsApp.</p></div><div className="grid gap-4 sm:grid-cols-2">{[[IdentificationCard,"Identitas asli","Peserta membawa KTP asli saat berada di Basecamp Ranu Pane."],[ShieldCheck,"Jaminan SIMAKSI","DP dikembalikan 100% apabila peserta tidak lolos proses SIMAKSI."],[UsersThree,"Data peserta","Perwakilan grup wajib mengisi formulir booking yang dikirim admin."],[CheckCircle,"Pembayaran","Nominal DP dapat didiskusikan dan pelunasan dilakukan H-1 keberangkatan."]].map(([Icon,title,text])=><div key={title as string} className="rounded-2xl border border-[#dfe6df] bg-white p-5"><Icon size={25} weight="fill" className="text-[#176b5b]"/><b className="mt-3 block">{title as string}</b><p className="mt-2 text-sm leading-6 text-[#6d7d78]">{text as string}</p></div>)}</div></div></section>

    <section className="container my-10 rounded-[30px] bg-[#d8f05a] p-9 sm:p-12"><div className="flex flex-wrap items-center justify-between gap-7"><div><div className="flex items-center gap-2 font-bold"><Mountains size={23} weight="fill"/> Private untuk grupmu</div><h2 className="mt-2 text-3xl font-extrabold">Siap bertemu Ranu Kumbolo?</h2><p className="mt-2 text-[#38564f]">Konsultasikan tanggal keberangkatan dan kebutuhan peserta bersama tim Aligatour.</p></div><a href="https://wa.me/628563532918?text=Halo%20Aligatour%2C%20saya%20ingin%20konsultasi%20Private%20Trip%20Ranu%20Kumbolo." className="btn-dark"><WhatsappLogo size={20} weight="fill"/> Konsultasi trip</a></div></section>
  </main>;
}
