import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, CalendarCheck, Camera, CheckCircle, MapPin, Mountains, UsersThree, WhatsappLogo, X } from "@phosphor-icons/react/dist/ssr";

export const metadata: Metadata = { title: "Open Trip Tumpak Sewu | Aligatour", description: "Open Trip Air Terjun Tumpak Sewu Rp350.000 per orang, berangkat setiap hari dari Malang dan Batu dengan tiket, guide, dan dokumentasi." };

const destinations = ["Panorama Tumpak Sewu", "Air Terjun Tumpak Sewu", "Telaga Biru", "Goa Tetes"];
const includes = ["Mobil", "BBM", "Driver", "Guide", "Tiket wisata", "Dokumentasi foto & video"];
const excludes = ["Transportasi dari kota asal ke meeting point", "Hotel", "Keperluan pribadi", "Baju ganti"];

export default function OpenTripTumpakSewuPage() {
  return <main className="min-h-screen bg-[#fbfcf8]">
    <section className="relative min-h-152.5 overflow-hidden bg-[#153d37] text-white"><Image src="/trip-cards/tumpak-sewu.jpg" alt="Air Terjun Tumpak Sewu" fill priority sizes="100vw" className="object-cover opacity-60"/><div className="absolute inset-0 bg-linear-to-r from-[#102f2b]/95 via-[#102f2b]/65 to-[#102f2b]/15"/><div className="container relative z-10 py-7"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-white/80"><ArrowLeft/> Kembali ke beranda</Link></div><div className="container relative z-10 pb-20 pt-16"><span className="inline-flex items-center gap-2 rounded-full bg-[#f7a72b] px-4 py-2 text-xs font-extrabold uppercase tracking-wider text-[#153d37]"><CalendarCheck weight="fill"/> Open Trip · Setiap Hari</span><h1 className="mt-6 max-w-4xl text-5xl font-extrabold tracking-[-.04em] sm:text-7xl">Air Terjun<br/><span className="text-[#d8f05a]">Tumpak Sewu</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/75">Jelajahi panorama air terjun ikonik dan destinasi alam di sekitarnya dalam satu hari perjalanan.</p><div className="mt-8 flex flex-wrap items-end gap-7"><div><small className="text-white/60">Harga per orang</small><p className="text-3xl font-extrabold text-[#d8f05a]">Rp350.000</p></div><a href="#booking" className="btn-primary">Reservasi trip <WhatsappLogo size={20} weight="fill"/></a></div></div></section>
    <section className="relative z-10 -mt-9"><div className="container"><div className="grid overflow-hidden rounded-2xl bg-white shadow-2xl shadow-[#153d3720] sm:grid-cols-3">{[[MapPin,"Meeting point","Kota Malang & Kota Batu"],[CalendarCheck,"Keberangkatan","Tersedia setiap hari"],[UsersThree,"Minimal peserta","4 orang per hari"]].map(([Icon,label,value])=><div key={label as string} className="flex items-center gap-4 border-b border-[#e8ece6] p-6 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><Icon size={27} weight="fill" className="shrink-0 text-[#176b5b]"/><div><small className="text-[#81908c]">{label as string}</small><b className="block">{value as string}</b></div></div>)}</div></div></section>
    <section className="py-24"><div className="container"><div className="max-w-2xl"><p className="eyebrow">Destinasi Trip</p><h2 className="mt-3 text-4xl font-extrabold">Empat pesona dalam sehari.</h2></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{destinations.map((item,index)=><div key={item} className="rounded-2xl border border-[#dfe6df] bg-white p-5"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#d8f05a] text-sm font-extrabold">{index+1}</span><Mountains size={25} weight="fill" className="mt-8 text-[#176b5b]"/><h3 className="mt-3 text-lg font-extrabold">{item}</h3></div>)}</div></div></section>
    <section className="bg-[#153d37] py-20 text-white"><div className="container grid gap-6 md:grid-cols-2"><div className="rounded-[26px] border border-white/12 bg-white/5 p-7"><h2 className="text-2xl font-extrabold">Sudah termasuk</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{includes.map(item=><div key={item} className="flex gap-3"><CheckCircle size={21} weight="fill" className="shrink-0 text-[#d8f05a]"/><span>{item}</span></div>)}</div></div><div className="rounded-[26px] bg-white p-7 text-[#153d37]"><h2 className="text-2xl font-extrabold">Belum termasuk</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{excludes.map(item=><div key={item} className="flex gap-3"><X size={20} weight="bold" className="shrink-0 text-[#b96a4c]"/><span>{item}</span></div>)}</div></div></div></section>
    <section className="py-20"><div className="container grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Syarat & Ketentuan</p><h2 className="mt-3 text-4xl font-extrabold">Tetap fleksibel saat kuota belum terpenuhi.</h2></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-[#eef1e6] p-6"><CalendarCheck size={27} weight="fill" className="text-[#176b5b]"/><b className="mt-4 block">Keberangkatan setiap hari</b><p className="mt-2 text-sm leading-6 text-[#6d7d78]">Trip berjalan saat kuota mencapai minimal empat peserta pada hari yang sama.</p></div><div className="rounded-2xl bg-[#eef1e6] p-6"><UsersThree size={27} weight="fill" className="text-[#176b5b]"/><b className="mt-4 block">Jika peserta di bawah empat</b><p className="mt-2 text-sm leading-6 text-[#6d7d78]">Pilih reschedule, beralih ke paket private trip, atau refund 100%.</p></div></div></div></section>
    <section id="booking" className="container mb-10 rounded-[30px] bg-[#d8f05a] p-9 sm:p-12"><div className="flex flex-wrap items-center justify-between gap-7"><div><div className="flex items-center gap-2 font-bold"><Camera size={23} weight="fill"/> Dokumentasi sudah termasuk</div><h2 className="mt-2 text-3xl font-extrabold">Siap melihat Tumpak Sewu?</h2><p className="mt-2 text-[#38564f]">Tentukan tanggal keberangkatanmu bersama Aligatour.</p></div><a href="https://wa.me/628563532918?text=Halo%20Aligatour%2C%20saya%20ingin%20reservasi%20Open%20Trip%20Tumpak%20Sewu." className="btn-dark"><WhatsappLogo size={20} weight="fill"/> Reservasi sekarang</a></div></section>
  </main>;
}
