import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, CalendarCheck, Camera, CheckCircle, MapPin, UsersThree, WhatsappLogo, X } from "@phosphor-icons/react/dist/ssr";

export const metadata: Metadata = { title: "Private Trip Tumpak Sewu | Aligatour", description: "Private Trip Tumpak Sewu mulai Rp400.000 per orang dengan meeting point Area Kota Malang, destinasi Tumpak Sewu, Goa Tetes, Telaga Biru, dan fasilitas dokumentasi lengkap." };

const destinations = ["Panorama Tumpak Sewu", "Goa Tetes", "Dasar Air Terjun Tumpak Sewu", "Telaga Biru"];
const includes = ["Transportasi PP area Malang - Tumpak Sewu", "Driver, BBM, & biaya parkir", "Tour guide", "Tiket masuk Tumpak Sewu", "Dokumentasi foto & video (all file)"];
const facilities = ["Snack & drink", "Full power bank", "Free Wi-Fi", "Insta360 X4 Air / Insta360 Ace Pro 2", "Photographer", "Edited photos", "Cinematic video"];
const gallery = [
  { src: "/trip-cards/tumpak-sewu.jpg", alt: "Tumpak Sewu" },
  { src: "/pricelists/tumpak-sewu.jpeg", alt: "Pricelist Tumpak Sewu" },
  { src: "/trip-cards/tumpak-sewu.jpg", alt: "Tumpak Sewu kedua" },
];

export default function OpenTripTumpakSewuPage() {
  return <main className="min-h-screen bg-[#fbfcf8]">
    <section className="relative min-h-142.5 overflow-hidden bg-[#153d37] text-white">
      <Image src="/trip-cards/tumpak-sewu.jpg" alt="Air Terjun Tumpak Sewu" fill priority sizes="100vw" className="object-cover opacity-60"/>
      <div className="absolute inset-0 bg-linear-to-r from-[#102f2b]/95 via-[#102f2b]/70 to-[#102f2b]/20"/>
      <div className="container relative z-10 py-7"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-white/80"><ArrowLeft/> Kembali ke beranda</Link></div>
      <div className="container relative z-10 pb-20 pt-20">
        <span className="inline-flex items-center gap-2 rounded-full bg-[#d8f05a] px-4 py-2 text-xs font-extrabold uppercase tracking-wider text-[#153d37]"><CalendarCheck weight="fill"/> Private Trip · Tumpak Sewu</span>
        <h1 className="mt-6 max-w-4xl text-5xl font-extrabold tracking-[-.04em] sm:text-7xl">Tumpak Sewu,<br/><span className="text-[#d8f05a]">khusus untuk rombonganmu.</span></h1>
        <p className="mt-6 max-w-2xl text-lg leading-8 text-white/75">Jelajahi panorama air terjun, Goa Tetes, Dasar Air Terjun Tumpak Sewu, dan Telaga Biru dalam trip private yang lebih rapi dan nyaman.</p>
        <div className="mt-8 flex flex-wrap items-end gap-6"><div><small className="text-white/60">Start from</small><p className="text-3xl font-extrabold text-[#d8f05a]">Rp400.000 <span className="text-sm text-white/70">/orang</span></p><span className="text-sm text-white/70">min. 3 orang</span></div><a href="#booking" className="btn-primary">Konsultasi trip <WhatsappLogo size={20} weight="fill"/></a></div>
      </div>
    </section>
    <section className="relative z-10 -mt-7"><div className="container"><div className="grid overflow-hidden rounded-[28px] bg-white shadow-2xl shadow-[#153d3720] sm:grid-cols-3">{[[MapPin,"Meeting point","Area Kota Malang"],[CalendarCheck,"Keberangkatan","Private trip sesuai request"],[UsersThree,"Minimal peserta","3 orang"]].map(([Icon,label,value])=><div key={label as string} className="flex items-center gap-4 border-b border-[#e8ece6] p-6 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><Icon size={27} weight="fill" className="shrink-0 text-[#176b5b]"/><div><small className="text-[#81908c]">{label as string}</small><b className="block">{value as string}</b></div></div>)}</div></div></section>
    <section className="py-24"><div className="container"><div className="flex flex-wrap items-end justify-between gap-6"><div className="max-w-2xl"><p className="eyebrow">Destinasi Trip</p><h2 className="mt-3 text-4xl font-extrabold">Empat spot utama dalam satu perjalanan.</h2><p className="mt-4 leading-7 text-[#6d7d78]">Paket ini fokus pada destinasi paling dicari di kawasan Tumpak Sewu dan sekitarnya, sesuai alur di poster terbaru.</p></div><div className="rounded-2xl bg-[#eef7f4] px-5 py-4"><div className="flex items-center gap-3"><MapPin size={27} weight="fill" className="text-[#176b5b]"/><div><b className="block text-sm">Area Kota Malang</b><span className="text-xs text-[#6d7d78]">Meeting point utama</span></div></div></div></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{destinations.map((item,index)=><div key={item} className="rounded-[22px] border border-[#dfe6df] bg-white p-5"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#d8f05a] text-sm font-extrabold text-[#153d37]">{index+1}</span><h3 className="mt-8 text-lg font-extrabold text-[#153d37]">{item}</h3><p className="mt-2 text-sm leading-6 text-[#6d7d78]">Spot pilihan untuk menikmati panorama tebing, air terjun, dan aliran sungai yang ikonik.</p></div>)}</div></div></section>
    <section className="bg-[#153d37] py-20 text-white"><div className="container grid gap-6 lg:grid-cols-2"><div className="rounded-[26px] border border-white/12 bg-white/5 p-7"><h2 className="text-2xl font-extrabold">Include</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{includes.map(item=><div key={item} className="flex gap-3"><CheckCircle size={21} weight="fill" className="shrink-0 text-[#d8f05a]"/><span>{item}</span></div>)}</div></div><div className="rounded-[26px] bg-white p-7 text-[#153d37]"><h2 className="text-2xl font-extrabold">Free Facilities</h2><p className="mt-2 text-sm text-[#6d7d78]">Fasilitas tambahan mengikuti materi promosi terbaru.</p><div className="mt-6 grid gap-4 sm:grid-cols-2">{facilities.map(item=><div key={item} className="flex gap-3"><CheckCircle size={21} weight="fill" className="shrink-0 text-[#176b5b]"/><span>{item}</span></div>)}</div><div className="mt-7 rounded-2xl bg-[#eef7f4] p-4 text-sm text-[#38564f]"><b>Bonus promo</b><span className="mt-1 block">Free panorama kapas biru tersedia selama promo berlangsung.</span></div></div></div></section>
    <section className="py-20"><div className="container grid gap-8 lg:grid-cols-[.95fr_1.05fr]"><div><p className="eyebrow">Kenapa trip ini</p><h2 className="mt-3 text-4xl font-extrabold">Private trip yang terasa lebih rapi dan nyaman.</h2><p className="mt-5 max-w-xl leading-7 text-[#6d7d78]">Mulai dari transport, dokumentasi, sampai fasilitas perjalanan, semuanya disusun supaya rombongan tinggal berangkat dan menikmati destinasi.</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-[#eef1e6] p-6"><Camera size={27} weight="fill" className="text-[#176b5b]"/><b className="mt-4 block">Dokumentasi all file</b><p className="mt-2 text-sm leading-6 text-[#6d7d78]">Foto dan video perjalanan disiapkan agar momen tetap lengkap setelah trip selesai.</p></div><div className="rounded-2xl bg-[#eef1e6] p-6"><UsersThree size={27} weight="fill" className="text-[#176b5b]"/><b className="mt-4 block">Min. 3 orang</b><p className="mt-2 text-sm leading-6 text-[#6d7d78]">Harga promo pada poster berlaku untuk keberangkatan dengan minimal tiga peserta.</p></div><div className="rounded-2xl bg-[#eef1e6] p-6"><MapPin size={27} weight="fill" className="text-[#176b5b]"/><b className="mt-4 block">Meeting point fleksibel</b><p className="mt-2 text-sm leading-6 text-[#6d7d78]">Fokus penjemputan dari area Kota Malang agar koordinasi lebih mudah.</p></div><div className="rounded-2xl bg-[#eef1e6] p-6"><CalendarCheck size={27} weight="fill" className="text-[#176b5b]"/><b className="mt-4 block">Berangkat sesuai request</b><p className="mt-2 text-sm leading-6 text-[#6d7d78]">Jadwal bisa disesuaikan dengan kebutuhan rombongan dan ketersediaan trip.</p></div></div></div></section>
    <section id="booking" className="container mb-10 rounded-[30px] bg-[#d8f05a] p-9 sm:p-12"><div className="flex flex-wrap items-center justify-between gap-7"><div><div className="flex items-center gap-2 font-bold"><Camera size={23} weight="fill"/> Dokumentasi dan fasilitas promo tersedia</div><h2 className="mt-2 text-3xl font-extrabold">Siap berangkat ke Tumpak Sewu?</h2><p className="mt-2 text-[#38564f]">Kirim tanggal, jumlah peserta, dan kebutuhan trip untuk kami bantu susun detailnya.</p></div><a href="https://wa.me/628563532918?text=Halo%20Aligatour%2C%20saya%20ingin%20konsultasi%20Private%20Trip%20Tumpak%20Sewu%20mulai%20Rp400.000%20untuk%20min.%203%20orang." className="btn-dark"><WhatsappLogo size={20} weight="fill"/> Konsultasi sekarang</a></div></section>
  </main>;
}
